'use strict';

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist-php');

function log(msg) {
  process.stdout.write(msg + '\n');
}

function resetDist() {
  const resolved = path.resolve(DIST);
  if (path.dirname(resolved) !== path.resolve(ROOT) || path.basename(resolved) !== 'dist-php') {
    throw new Error('Refusing to clean unexpected path: ' + resolved);
  }
  fs.rmSync(resolved, { recursive: true, force: true });
  fs.mkdirSync(resolved, { recursive: true });
}

function copyDir(src, dest, skip = () => false) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const rel = entry.name;
    if (skip(rel)) continue;
    const s = path.join(src, rel);
    const d = path.join(dest, rel);
    if (entry.isDirectory()) {
      copyDir(s, d, skip);
    } else if (entry.isFile()) {
      fs.copyFileSync(s, d);
    }
  }
}

function writeIfChanged(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function generateSchema() {
  const storage = fs.readFileSync(path.join(ROOT, 'storage.js'), 'utf8');
  const start = storage.indexOf('const TABLES={');
  const end = storage.indexOf('const toMysql');
  if (start === -1 || end === -1 || end < start) {
    throw new Error('Unable to locate TABLES in storage.js');
  }
  const block = storage.slice(start, end);
  const re = /(\w+):`([\s\S]*?)`/g;
  const statements = [];
  let m;
  while ((m = re.exec(block))) {
    statements.push(m[2].trim().replace(/;?$/, ';'));
  }
  const jobsFragment = path.join(ROOT, 'php', '_app', 'sql', 'jobs.sql.fragment');
  statements.push(fs.readFileSync(jobsFragment, 'utf8').trim());
  const sql = '-- Generated by scripts/build-php.js. Do not edit.\n'
    + '-- Import into the cPanel database via phpMyAdmin.\n\n'
    + statements.join('\n\n') + '\n';
  writeIfChanged(path.join(DIST, '_app', 'sql', 'schema.sql'), sql);
  log('  generated _app/sql/schema.sql (' + statements.length + ' tables)');
}

function lintPhp() {
  const probe = spawnSync('php', ['-v'], { encoding: 'utf8' });
  if (probe.error || probe.status !== 0) {
    log('  php not found on PATH; skipping lint');
    return;
  }
  const files = [];
  (function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(p);
      else if (entry.name.endsWith('.php')) files.push(p);
    }
  })(DIST);
  let bad = 0;
  for (const file of files) {
    const r = spawnSync('php', ['-l', file], { encoding: 'utf8' });
    if (r.status !== 0) {
      bad++;
      process.stderr.write(r.stdout + r.stderr);
    }
  }
  if (bad) throw new Error(bad + ' PHP file(s) failed lint');
  log('  linted ' + files.length + ' PHP files');
}

function zipDist() {
  const probe = spawnSync('zip', ['-v'], { encoding: 'utf8' });
  if (probe.error || probe.status !== 0) {
    log('  zip not found on PATH; skipping dist-php.zip');
    return;
  }
  const out = path.join(ROOT, 'dist-php.zip');
  const r = spawnSync('zip', ['-r', '-q', '-FS', out, 'dist-php'], { cwd: ROOT, encoding: 'utf8' });
  if (r.status !== 0) {
    process.stderr.write(r.stdout + r.stderr);
    throw new Error('zip failed');
  }
  log('  wrote dist-php.zip');
}

function main() {
  log('Building dist-php/');
  resetDist();

  copyDir(path.join(ROOT, 'public'), DIST);
  log('  copied public/');

  copyDir(path.join(ROOT, 'php', '_app'), path.join(DIST, '_app'), (name) => name === 'config.php' || name === 'htaccess-deny' || name === 'uploads');
  copyDir(path.join(ROOT, 'php', 'api'), path.join(DIST, 'api'));
  copyDir(path.join(ROOT, 'php', 'admin'), path.join(DIST, 'admin'));
  for (const f of ['job.php', 'apply.php', 'sitemap.php']) {
    fs.copyFileSync(path.join(ROOT, 'php', f), path.join(DIST, f));
  }
  log('  copied php/');

  const adminDir = path.join(DIST, 'admin');
  fs.mkdirSync(adminDir, { recursive: true });
  for (const f of ['admin.html', 'admin.js']) {
    fs.copyFileSync(path.join(ROOT, 'admin', f), path.join(adminDir, f));
  }
  log('  copied admin UI');

  copyDir(path.join(ROOT, 'data'), path.join(DIST, '_app', 'data'), (name) => name !== 'chatbot.json');
  log('  copied chatbot knowledge base');

  writeIfChanged(path.join(DIST, '.htaccess'), fs.readFileSync(path.join(ROOT, 'php', 'htaccess.template'), 'utf8'));
  writeIfChanged(path.join(DIST, '_app', '.htaccess'), fs.readFileSync(path.join(ROOT, 'php', '_app', 'htaccess-deny'), 'utf8'));
  log('  generated .htaccess files');

  generateSchema();

  writeIfChanged(path.join(DIST, 'DEPLOY.md'), fs.readFileSync(path.join(ROOT, 'php', 'DEPLOY.md.template'), 'utf8'));
  log('  wrote DEPLOY.md');

  lintPhp();
  zipDist();
  log('Done. Upload dist-php/ (or dist-php.zip) contents to the document root.');
}

try {
  main();
} catch (err) {
  console.error('Build failed: ' + err.message);
  process.exit(1);
}
